### ISSUE TITLE
Register allows registration with a taken email

### ISSUE THREAD

**Issue by BenAlderfer** [rit-sse/CoursePlanner#112]
A user can register with an email that's been taken. It throws the email taken error but still logs them in.

**Comment by khanny17** [comment]
Unable to reproduce in production

**Comment by khanny17** [comment]
Still wasnt able to reproduce, locally. I'm going to guess you encountered this because in your dev environment, when you reboot the server I believe starts from a new mongo database each time. If we encounter this in production i'll reopen the ticket.
