### ISSUE TITLE
Workspace Button Rework

### ISSUE THREAD

**Issue by khanny17** [rit-sse/CoursePlanner#32]
We mentioned moving around a few functional components in issue #31 such as:
* Moving the Delete Year button to be inside the year header
* Relocating the Add Semester button to somewhere that saves more space
* Moving the Plan Title to the navbar

In addition to these points, the size and location of all the other buttons in the workspace (Add course, delete semester, add year) can be reconsidered.

**Comment by BenAlderfer** [comment]
This image shows the proposed new delete year and add semester buttons. What do you think? 

![plan](https://cloud.githubusercontent.com/assets/9043915/24522347/49fc9f8c-155d-11e7-8ead-706864a59f7a.png)

**Comment by khanny17** [comment]
The X in the Year header should be right aligned, the add semester button is definitely too large, and I think we should add an X icon to the semester delete buttons. Also, I think maybe we shouldn't have the delete buttons showing all the time. Maybe they could only appear when you hover over the semester?

I'm not sure how to change the add semester button. Maybe if we make it thinner, and also only have it appear when you mouse over the year? That might be too many things moving around at once, but I also feel that it is important our design is minimalist. The most important thing is that the user can **look** at the plan. Adding and deleting years is a very uncommon task (how many times do you change your mind about how many years you are going to be in school?), and adding and deleting semesters is a very uncommon task (how many people are taking classes during the summer?). Adding and deleting courses, on the other hand, is more common.

We want all the buttons out of the way. The main use case is the user has 4 years, 2 semesters per year, with 4-6 classes in each semester. That's a LOT. It's a lot of color, it's a lot of information. Our UI needs to get out of the way as much as possible, so someone can open their plan, lean back in their chair, and just observe and think.

**Comment by khanny17** [comment]
I think what I will do is set up a server to build the "ben" branch, from here on out. I still want you to post screenshots because it makes discussion easy, but this way when we are doing things like buttons that pop up when you mouse over, we can go and see how it _feels_.

**Comment by BenAlderfer** [comment]
That makes sense. I'll see what I can do with hover to make buttons appear. 

Before setting up the build branch, I've been considering renaming my branch to be more descriptive/less exclusive. Do you have any ideas for that?

**Comment by BenAlderfer** [comment]
Also, I think moving the plan title to the navbar isn't going to be an option. Its already full on smaller screens: 

![overflow](https://cloud.githubusercontent.com/assets/9043915/24524630/52a9cbfc-1565-11e7-9638-0eb4453d31ee.png)

Some sites such as Trello just keep the name and some associated actions below the navbar: 

![trello](https://cloud.githubusercontent.com/assets/9043915/24524651/6341341e-1565-11e7-887b-c92cf5cf9283.png)

I'm thinking keeping the title below the navbar, maybe left aligning, and moving some navbar actions down next to it. Probably save and the plan dropdown would make sense.

**Comment by khanny17** [comment]
We can name the branch design, or design-changes. I like your navbar plans. It gives us more flexibility when it comes to adding advanced actions. Lets make sure we keep it small though. I like how the size of Trello's navbars, I think if we could emulate their size that would be good.

**Comment by BenAlderfer** [comment]
The branch is "design-changes" now.

**Comment by BenAlderfer** [comment]
Ideas from meeting: 

- change delete year to ellipsis and move add semester to that
- make add course thinner and match class width
- move delete semester into the course list and use the same style as delete year currently
- center year title regardless of ellipsis
