### ISSUE TITLE
Course Rework

### ISSUE THREAD

**Issue by khanny17** [rit-sse/CoursePlanner#41]
The look of the courses should be redesigned to be prettier!

Here is a starting thought: 
![image](https://cloud.githubusercontent.com/assets/5606468/24638014/4e973f58-18b3-11e7-8f2c-c1203dd17501.png)

**Comment by BenAlderfer** [comment]
Made some changes to the latest version. The design server seems to be working again so you can see it [here](http://98.10.62.15/). Main changes are more side padding and drop shadows so the courses stand out more.
