### ISSUE TITLE
Input a bunch of RIT default plans

### ISSUE THREAD

**Issue by khanny17** [rit-sse/CoursePlanner#52]
Before Imagine, we should put in several RIT degree plans and make them public. That way people checking out the application can load them in and get right to experimenting with it with their own plan

**Comment by BenAlderfer** [comment]
Will making plans public work locally or will we have to use the ssedev site?

**Comment by khanny17** [comment]
Your local machine uses a local database, so no. Nothing you do on your local machine should affect ssedev. Which by the way is down and i need to talk to timbrook
