### ISSUE TITLE
Improve help modal

### ISSUE THREAD

**Issue by khanny17** [rit-sse/CoursePlanner#7]
When the user first comes to the application, there is a very good chance they will have no idea what to do. Making a useful help modal could be a simple step that would make it much easier for the user to learn how to use the application, and also retain potential users who might otherwise leave the app because "I don't get it".

**Comment by Michael-Longley** [comment]
What changes did you have in mind. I see the download is wrong but anything else in particular?

**Comment by Michael-Longley** [comment]
![help-modal-update](https://cloud.githubusercontent.com/assets/15826968/25732963/ceb11bdc-3122-11e7-8fd3-58c99b7aeda0.png)
How does this look for the new modal?

**Comment by khanny17** [comment]
Perfect!

**Comment by Michael-Longley** [comment]
![helpmodalupdated](https://cloud.githubusercontent.com/assets/15826968/25733254/54b80df6-3125-11e7-8b4a-5b18d3514daa.png)
Changed a bit of the wording and spacing.
