### ISSUE TITLE
Docker not working with Mongo.

### ISSUE THREAD

**Issue by Michael-Longley** [rit-sse/CoursePlanner#78]
![dockerissue](https://cloud.githubusercontent.com/assets/15826968/25619659/a8de1028-2f19-11e7-849a-bd288d9d22c8.PNG)
Trying to run docker to build the project results in this output.

**Comment by khanny17** [comment]
Is this still something that should be an issue?

**Comment by akath20** [comment]
Well this is a Windows issue
